spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Zc1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /test

mybatis:
  mapper-locations: com/example/demo1/mapper/*.xml